version: "3.7"
services:
  mkcert:
    build: .
    volumes:
      - certca:/root/.local/share/mkcert/
      - certdata:/certs

  server:
    build: ./server
    depends_on:
      - mkcert # need certca and certdata volumes filled
    networks:
      net:
        aliases:
          - faraday-live.localhost
    volumes:
      - certca:/root/.local/share/mkcert/:ro
      - certdata:/certs:ro
      - ./server/run.sh:/app/run.sh

  tests:
    build: ./tests
    depends_on:
      - server
    networks:
      - net
    environment:
      - HTTP_URL=http://faraday-live.localhost
      - HTTPS_URL=https://faraday-live.localhost
    volumes:
      - certca:/root/.local/share/mkcert/:ro
      - certdata:/certs:ro
      - ./tests/lib:/app/lib
      - ./tests/run.sh:/app/run.sh

volumes:
  certca:
  certdata:

networks:
  net:
