FROM alpine

RUN set -xe \
    && apk add --no-cache bash tinyproxy \
    && sed -i -e '/^Allow /s/^/#/' \
              -e '/^ConnectPort /s/^/#/' \
              /etc/tinyproxy/tinyproxy.conf

VOLUME /etc/tinyproxy
EXPOSE 8888

COPY tinyproxy.sh .

CMD ./tinyproxy.sh
