version: "3.7"
services:
  mkcert:
    build:
      context: .
      args:
        host: faraday-live.localhost live-proxy.localhost
    volumes:
      - certca:/root/.local/share/mkcert/
      - certdata:/certs

  proxy:
    build: ./proxy
    depends_on:
      - mkcert # need certca and certdata volumes filled
    networks:
      net:
        aliases:
          - live-proxy.localhost
    volumes:
      - certca:/root/.local/share/mkcert/:ro
      - certdata:/certs:ro
      - ./proxy/run.sh:/app/run.sh

  server:
    build: ./server
    depends_on:
      - mkcert # need certca and certdata volumes filled
    networks:
      net:
        aliases:
          - faraday-live.localhost
    volumes:
      - certca:/root/.local/share/mkcert/:ro
      - certdata:/certs:ro
      - ./server/run.sh:/app/run.sh

  tests:
    build:
      context: ./tests
      args:
        faraday_gem_ref: ${FARADAY_GEM_REF:-master}
        faraday_http_gem_ref: ${FARADAY_HTTP_GEM_REF:-master}
        socksify_gem_ref: ${FARADAY_SOCKSIFY_GEM_REF:-master}
    depends_on:
      - server
      - proxy
    networks:
      - net
    environment:
      - HTTP_HOST=faraday-live.localhost
      - PROXY_HOST=live-proxy.localhost
      - TEST_ADAPTER=${TEST_ADAPTER:-}
      - TEST_METHOD=${TEST_METHOD:-}
      - TEST_PROTO=${TEST_PROTO:-}
    volumes:
      - certca:/root/.local/share/mkcert/:ro
      - certdata:/certs:ro
      - ./tests/spec:/app/spec
      - ./tests/.rspec:/app/.rspec
      - ./tests/run.sh:/app/run.sh

volumes:
  certca:
  certdata:

networks:
  net:
