source 'https://rubygems.org'
gem 'bundler'
gem 'em-http-request', '>= 1.1', require: 'em-http'
gem 'em-synchrony', '>= 1.0.3', require: %w[em-synchrony em-synchrony/em-http]
gem 'excon', '>= 0.27.4'
gem 'httpclient', '>= 2.2'
gem 'net-http-persistent'
gem 'patron', '>= 0.4.2', platforms: :ruby
gem 'rake'
gem 'rspec'
gem 'socksify', git: 'https://github.com/astro/socksify-ruby', ref: 'dae610084b4cebd0af92731dbf29f3dd9b9fd9d6'
gem 'typhoeus', '~> 1.3'
